### ISSUE TITLE
Requests for Functionality: Ability for Buttons to be placed inside Draggables + Draggables Parent Container Validation Array

### ISSUE THREAD

**Issue by Shadowblight** [don-tnowe/godot-extra-controls#10]
First off thank you for your incredible work on this plugin. I found this when trying to explore solutions on how to do some really common things with UI that I found out that Godot simply tells you to "figure it out yourself"...

I also love the other plugin you have to view Resources as Sheets. :)

Anyway, my question is: I would like to be able to combine functionality of the draggable with a button. Currently whenever I put a button nested as a child into a Draggable with a ColorRect as a simple background (though this could be implemented as a TextureRect or other element type), it completely disregards the draggable functionality. Draggable nodes are set to Stop by default, but even if I set one or both of them to pass, it doesn't allow any part of it to be dragged. If I have both the Draggable and Rect in Pass it let's me pick the button, but then it thinks I'm trying to resize the button whenever I click the background to use it. If the ColorRect is set to anything besides Ignore, it also fails to move even with no button present. So long and short, it'd interact with the button if it's visible on render from its control siblings/parent, but otherwise the mouse will just go about its business to allow dragging.

Also, may I suggest that Draggables have a means via Array in the inspector to define specific "valid" parent controls to be dropped into? And that if it is not dropped in the area of that container it returns to the edge of the originating parent container, just like how it does if it's told to stay in bounds currently and it attempts to go out of bounds. In an ideal situation it'd even have the hover ghost have a highlight to permit showing when it's going into a valid container with theming potential, but obviously that could be tossed well on the backburner to just having the functionality, lol.

**Comment by don-tnowe** [comment]
Yea, controls inside Draggable nodes will block input unless set to Ignore. If a button is stretched to the full extents of the Draggable, it would have to ignore input to not cover up the Draggable's "move" area. However, nodes inside can have anything else in them,  including buttons resized in any way.

If the need is to allow the button to move the node when grabbed, extra behaviour would be needed to prevent it from being clicked when moving it. So, try making a script that extends `Draggable`!

The base class stores an initial position to let you check drag distance (*so the button only presses if not dragged*), and you can define additional `_gui_input()` behaviour to emulate a button - just don't forget to call `super()`.

The second suggestion sounds like a niche feature, but I'll consider it! Sounds like how `InterpolatedContainer` works.

**Comment by don-tnowe** [comment]
I'll be closing this to keep feature discussion in #11 and #12!

**Comment by don-tnowe** [comment]
`InterpolatedFreeContainer`, a container that allows dragging children freely and transferring between, should be already up on the main branch if still needed 😉
