### ISSUE TITLE
Adding one child from code to `InterpolatedBoxContainer` returns an infinite vector error spam.

### ISSUE THREAD

**Issue by INdIEDeV016** [don-tnowe/godot-extra-controls#16]
![image](https://github.com/user-attachments/assets/780cf355-cdec-428e-8dc0-8847ce7dfba3)

I am trying to create a `InterpolatedBoxContainer` and add a `Button` Node to the container. All this is done from code.

```gd
func _ready() -> void:
	for index in %Header.get_children().size():
		var container: = InterpolatedBoxContainer.new()
		container.vertical = true
		container.move_time = 0.3
		container.easing_factor = 0.2
		container.allow_drag_insert = true
		container.allow_drag_transfer = true

		if OS.is_debug_build():
			var button = Button.new()
			button.text = "Status"
			button.custom_minimum_size = Vector2(75, 50)
			button.size = Vector2(75, 50)
			container.add_child(button)

	%Body.add_child(container)
```

I have not tested this with other nodes, so I don't know, if this error comes up with other nodes as well.

**Comment by don-tnowe** [comment]
The node does not use `get_children()` with the first parameter set to `true`. Changing it in the code should fix it, I'll do it later when I get to it.
